
create table account (
    id int8 generated by default as identity,
    type int8 not null,
    lead_id int8 not null,
    primary key (id)
                     );
create table lead (
    id int8 generated by default as identity,
    dateof_birth timestamp, email varchar(255),
    first_name varchar(255), gender boolean not null,
    last_name varchar(255),
    login varchar(255),
    middle_name varchar(255),
    password varchar(255),
    phone_number varchar(255),
    primary key (id)
                  );
create table subscription_type (
    id int8 generated by default as identity,
    title varchar(255),
    primary key (id)
                               );

alter table if exists account add constraint FKdla8jxchbmuf5yxyyp39ygf58 foreign key (type) references subscription_type;

alter table if exists account add constraint FKgva8br7vnn3jjug9oeygf6bgx foreign key (lead_id) references lead;


